title: EEECS Lego Lab
description: The EEECS Lego Lab is a multidisciplinary space for students to develop technology enhancements aimed at improving the world around us.
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
