title: EEECS Lego Lab
description: The EEECS Lego Lab is a multidisciplinary space for students to develop technology enhancements aimed at improving the world around us.
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
include: ['_pages']
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"
  - scope:
      path: "_posts/projects"
    values:
      type: "project"
      layout: "project"
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
      layout: "blog"
